apiVersion: v1
kind: Pod
metadata:
  name: guestbook
  labels:
    name: guestbook
spec:
  containers:
  - name: myapp
    image: mrdunski/guestbook:0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    livenessProbe:
      httpGet:
        port: http
        path: /api/health/liveness
    readinessProbe:
      httpGet:
        port: http
        path: /api/health/readiness
